def _render_ai_simulation_builder(ai_engine):
    ...

def _render_script_generator(ai_engine):
    ...

def _render_simulation_runner():
    ...

def _render_virtual_labs():
    ...

def _render_simulation_library():
    ...

def _build_scenario_prompt(...):
    ...

def _build_code_prompt(...):
    ...
